# Generated by Django 2.2.17 on 2021-01-16 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30, verbose_name='订单标题')),
                ('body', models.CharField(default='', max_length=30, verbose_name='订单内容')),
                ('status', models.CharField(default='New', max_length=10, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户id')),
            ],
            options={
                'ordering': ['create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=30, verbose_name='昵称')),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='手机')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.CharField(default='', max_length=30, verbose_name='个人简介')),
                ('score', models.BigIntegerField(default=0, verbose_name='积分')),
                ('user_group', models.CharField(default='C', max_length=1, verbose_name='用户组')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
            },
        ),
        migrations.RemoveField(
            model_name='posts',
            name='article_id',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='profileapi',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.DeleteModel(
            name='ProfileAPI',
        ),
    ]
