# Generated by Django 2.2.17 on 2021-01-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20210116_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_group',
            field=models.SmallIntegerField(choices=[(1, 'customer'), (2, 'executor')], default=1, verbose_name='用户组'),
        ),
    ]
