# Generated by Django 2.2.17 on 2021-01-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0003_auto_20210116_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'New'), (2, 'Cancelled')], default=1, verbose_name='订单状态'),
        ),
    ]
