# Generated by Django 2.2.13 on 2020-10-29 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('evaluate', models.CharField(max_length=500)),
                ('stars', models.CharField(max_length=5)),
            ],
        ),
    ]
